version: "3.8"

services:
  php_fpm:
      build: .
      container_name: imagine_php_fpm
      restart: always
      working_dir: /usr/share/nginx/imagine
      networks:
          - imagine
      volumes:
          - ./:/usr/share/nginx/imagine
          - ./docker/php/php.ini:/usr/local/etc/php/php.ini

  nginx:
      image: nginx:1.18
      container_name: imagine_nginx
      restart: always
      working_dir: /usr/share/nginx/imagine
      networks:
          - imagine
      ports:
          - "443:443"
      volumes:
          - ./:/usr/share/nginx/imagine
          - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
          - ./docker/nginx/ssl/try2imagine.local.crt:/etc/nginx/ssl/try2imagine.local.crt
          - ./docker/nginx/ssl/try2imagine.local.key:/etc/nginx/ssl/try2imagine.local.key

networks:
  imagine:
    driver: bridge
